title: Gabriel Magdaleno  
author: gmagdaleno
email: gmagdaleno1981@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Este es un blog creado durante la creación de GitHub pages en el GitHub Learning Lab.

# social links
twitter_username: gmagdaleno # DO NOT include the @ character, or else the build will fail!
github_username:  gabrielmagdaleno # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
